services:
  # Backend API Service
  - type: web
    name: nosana-github-insights-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GITHUB_TOKEN
        sync: false  # Will be set manually in Render dashboard

  # Frontend Static Site
  - type: static
    name: nosana-github-insights-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/build
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 